name: "Build"
on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    env:
      CMAKE_CXX_COMPILER_LAUNCHER: ccache
      CMAKE_C_COMPILER_LAUNCHER: ccache
    steps:
      - uses: actions/checkout@v5

      - name: Install Clang
        run: cd /tmp;
          wget https://apt.llvm.org/llvm.sh;
          chmod +x llvm.sh;
          sudo ./llvm.sh 20

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          create-symlink: true

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '4.1.x'

      - name: Install Just
        uses: extractions/setup-just@v3

      - name: Install Conan
        uses: conan-io/setup-conan@v1
        with:
          cache_packages: true

      - name: Setup Conan profile
        run: conan profile detect --force

      - name: Install more system deps
        run: sudo apt update; sudo apt install --yes clang ninja-build

      - name: Build deps
        run: just conan

      - name: Build
        run: just build
        env:
          CC: clang-20
          CXX: clang++-20

      - name: Archive artefacts
        uses: actions/upload-artifact@v4
        with:
          name: musicvis3d
          path: build/musicvis
